### ISSUE TITLE
Help with execute

### ISSUE THREAD

**Issue by BLCKEAGLE4** [luohongming/CISR_PSI#2]
Your paper is very inspiring! If it is possible, I want to know what are the steps with the commands execute your project. Do I need to resize the images of your dataset(UCD76,WeChat) in matlab, and how I can do this? I'm doing my thesis for my degree on your paper and I would be grateful if you could help me!

**Comment by luohongming** [comment]
You need to prepare UCD76 first and the MatLab code in directory data/. Then run ''bash train.sh'' or ''bash eval.sh''.

**Comment by BLCKEAGLE4** [comment]
Thank you for your rapid response. I can't extract UCD76 but I can the wechat.
![image](https://user-images.githubusercontent.com/43848909/115107891-232c5f80-9f76-11eb-892f-db276e86a817.png)

Also, you specify paths like "/home/luo/data/super-resolution/DIV2K+"  , so how I can figure out where is DIV2K+ or DIV2K_val or VISTA(data/save_webp_file.py)?
 Is it necessary to download the pre-trained models?
Thank you

**Comment by luohongming** [comment]
You need to change '/home/luo/data/super-resolution/DIV2K+' to your path.  And I have uploaded the UCD76 and Wechat dataset on Baidu link: https://pan.baidu.com/s/1eF41V3jnQnR_1CwuD1PYkA   password: 1xuj
